runtime: nodejs20

handlers:
  # Serve index.html à la racine
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  # Serve tous les fichiers du dossier dist/assets
  - url: /assets
    static_dir: dist/assets

  # Serve le CSS et JS (Vite met souvent tout dans assets, donc déjà couvert)

  # Proxy API to backend when deployed behind same service (optional example)
  - url: /api/.*
    script: auto

env_variables:
  DB_URL: "postgres://fright_app:App!Fright2025@/fright_finds?host=/cloudsql/fright-finds-hub:europe-west9:fright-finds-sql"
  NODE_ENV: "production"
  NPM_CONFIG_PRODUCTION: "true"

beta_settings:
  cloud_sql_instances: "fright-finds-hub:europe-west9:fright-finds-sql"

automatic_scaling:
  max_instances: 3
  min_instances: 0